version: '3.3'

services:
  db:
    image: 'postgres:16'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db

  api:
    build:
      context: ./bookstoreapi
    ports:
      - 8000:8000
      - 8080:8080
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
      - api_user
      - api_password
      - api_role

secrets:
  postgres_user:
    file: db/secrets/postgres_user
  postgres_password:
    file: db/secrets/postgres_password
  postgres_db:
    file: db/secrets/postgres_db
  api_user:
    file: bookstoreapi/secrets/defaultuser_username
  api_password:
    file: bookstoreapi/secrets/defaultuser_password
  api_role:
    file: bookstoreapi/secrets/defaultuser_role
